"""Agrandar tamanio de descripcion ingreso/egreso

Revision ID: 173836f9f9f9
Revises: aae412e4ac40
Create Date: 2024-08-31 09:53:33.046962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173836f9f9f9'
down_revision = 'aae412e4ac40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egreso', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingreso', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('egreso', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###
