"""crear seguimiento de venta y de cobranza

Revision ID: 210c79b7342e
Revises: 6410671f89c6
Create Date: 2024-08-19 14:36:31.643247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210c79b7342e'
down_revision = '6410671f89c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguimiento_cobranza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('detalle', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguimiento_venta')
    op.drop_table('seguimiento_cobranza')
    # ### end Alembic commands ###
