"""Agregar on cascade cuando se borra venta

Revision ID: 3cc5fd505ec6
Revises: 173836f9f9f9
Create Date: 2024-09-10 11:29:00.110283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc5fd505ec6'
down_revision = '173836f9f9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'venta', ['venta_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cuota', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'venta', ['venta_id'], ['id'])

    # ### end Alembic commands ###
