"""Agregar modelo de pagos de cuotas

Revision ID: 6410671f89c6
Revises: d2e9d637d344
Create Date: 2024-08-17 12:45:11.702373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6410671f89c6'
down_revision = 'd2e9d637d344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago_cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuota_id', sa.Integer(), nullable=False),
    sa.Column('monto_pago', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cuota_id'], ['cuota.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_cuota')
    # ### end Alembic commands ###
