"""volver nuleable ventas.entrega_inicial

Revision ID: 8d6252b3cf9b
Revises: c43607d78bd8
Create Date: 2024-08-17 10:42:13.868603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6252b3cf9b'
down_revision = 'c43607d78bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.alter_column('entrega_inicial',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.alter_column('entrega_inicial',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
