"""Agregar fecha de próximo contacto a seguimiento de venta3

Revision ID: aae412e4ac40
Revises: 491b035e9f68
Create Date: 2024-08-29 18:19:07.822007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae412e4ac40'
down_revision = '491b035e9f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimiento_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_proximo_contacto', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seguimiento_venta', schema=None) as batch_op:
        batch_op.drop_column('fecha_proximo_contacto')

    # ### end Alembic commands ###
