"""Agregar temas para flujo de caja

Revision ID: b8e5ffaebc69
Revises: 210c79b7342e
Create Date: 2024-08-27 16:24:58.724490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e5ffaebc69'
down_revision = '210c79b7342e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=25), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('tasa_cambio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingreso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=25), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('importe', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('tasa_cambio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['concepto_id'], ['concepto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_venta')
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_interno', sa.String(length=10), nullable=True))
        batch_op.drop_column('CODIGO_INTERNO')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CODIGO_INTERNO', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('codigo_interno')

    op.create_table('_alembic_tmp_venta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo_interno', sa.VARCHAR(length=10), nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), nullable=False),
    sa.Column('producto_id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('tipo_pago', sa.VARCHAR(length=20), nullable=False),
    sa.Column('entrega_inicial', sa.FLOAT(), nullable=True),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingreso')
    op.drop_table('egreso')
    op.drop_table('concepto')
    # ### end Alembic commands ###
