"""Agregar campo teléfono al modelo Cliente

Revision ID: d2e9d637d344
Revises: 85d87ae1ddef
Create Date: 2024-08-17 12:29:17.921001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e9d637d344'
down_revision = '85d87ae1ddef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
